name: calinga
description: "CALiNGA - On-Demand Care Application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  # Core Firebase
  firebase_core: ^4.0.0

  # Firebase Services
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.0
  firebase_auth_platform_interface: ^8.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

  # Your other dependencies (unchanged)
  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  intl: ^0.20.2
  flutter_svg: ^2.2.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
