// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLl3YsfhcgPBJe4paDXQOqmgj_LEXo5X8',
    appId: '1:124822117175:web:16eba1912b343d6fcfd8b2',
    messagingSenderId: '124822117175',
    projectId: 'callinga-d6829',
    authDomain: 'callinga-d6829.firebaseapp.com',
    storageBucket: 'callinga-d6829.firebasestorage.app',
    measurementId: 'G-5DE38WGGK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkdh_qa7KZ_qVIeEWE1HLWeeVlHNR9vJo',
    appId: '1:124822117175:android:afca6a6044911f79cfd8b2',
    messagingSenderId: '124822117175',
    projectId: 'callinga-d6829',
    storageBucket: 'callinga-d6829.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzfOlD9ajGXwrbFFFkqyIUrjxvQNUhd6M',
    appId: '1:124822117175:ios:a356df69f3d8e705cfd8b2',
    messagingSenderId: '124822117175',
    projectId: 'callinga-d6829',
    storageBucket: 'callinga-d6829.firebasestorage.app',
    iosBundleId: 'com.example.calinga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzfOlD9ajGXwrbFFFkqyIUrjxvQNUhd6M',
    appId: '1:124822117175:ios:a356df69f3d8e705cfd8b2',
    messagingSenderId: '124822117175',
    projectId: 'callinga-d6829',
    storageBucket: 'callinga-d6829.firebasestorage.app',
    iosBundleId: 'com.example.calinga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLl3YsfhcgPBJe4paDXQOqmgj_LEXo5X8',
    appId: '1:124822117175:web:d906cc7197afe8b2cfd8b2',
    messagingSenderId: '124822117175',
    projectId: 'callinga-d6829',
    authDomain: 'callinga-d6829.firebaseapp.com',
    storageBucket: 'callinga-d6829.firebasestorage.app',
    measurementId: 'G-MTYFBWLMG5',
  );
}
